#
# Copyright 2025 Ezurio
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += nitrogen_imx8mp.o 
obj-y += lpddr4_patches.o 
obj-y += ../common/imx-common.o

obj-$(CONFIG_SPL_BUILD) += spl.o 
obj-$(CONFIG_SPL_BUILD) += lpddr4_timing.o
