#
# Copyright 2025 Ezurio LLC
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += nitrogen_imx93.o ../common/imx-common.o

ifdef CONFIG_XPL_BUILD
obj-y += spl.o lpddr4x_1gb_timing.o lpddr4x_2gb_timing.o
endif
