#
# Copyright 2022 NXP
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += nitrogen_imx93.o ../common/imx-common.o

ifdef CONFIG_XPL_BUILD
obj-y += spl.o
obj-y += lpddr4x_timing.o lpddr4x_timing_1866mts.o
endif
