#
# Copyright 2026 Ezurio LLC
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += nitrogen_imx8mm.o 
obj-y += lpddr4_patches.o 
obj-y += ../common/imx-common.o

obj-$(CONFIG_XPL_BUILD) += spl.o 
obj-$(CONFIG_XPL_BUILD) += lpddr4_timing.o
