#
# Copyright 2026 Ezurio LLC
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += nitrogen_imx91.o ../common/imx-common.o

ifdef CONFIG_XPL_BUILD
obj-y += spl.o
obj-y += lpddr4_timing_2400mts.o lpddr4_timing_1600mts.o
endif
